/*
 * Code for class WEL_CLIPBOARD_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1021_9380(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9381(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9382(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9383(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9384(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9385(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9386(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9387(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9388(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9389(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9390(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9391(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9392(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1021_9393(EIF_REFERENCE);
extern void EIF_Minit1021(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_CLIPBOARD_CONSTANTS}.cf_text */
EIF_TYPED_VALUE F1021_9380 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_bitmap */
EIF_TYPED_VALUE F1021_9381 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_metafile_picture */
EIF_TYPED_VALUE F1021_9382 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_sylk */
EIF_TYPED_VALUE F1021_9383 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_dif */
EIF_TYPED_VALUE F1021_9384 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_tiff */
EIF_TYPED_VALUE F1021_9385 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_oemtext */
EIF_TYPED_VALUE F1021_9386 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_dib */
EIF_TYPED_VALUE F1021_9387 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_palette */
EIF_TYPED_VALUE F1021_9388 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_pendata */
EIF_TYPED_VALUE F1021_9389 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_riff */
EIF_TYPED_VALUE F1021_9390 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_wave */
EIF_TYPED_VALUE F1021_9391 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_unicodetext */
EIF_TYPED_VALUE F1021_9392 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_CLIPBOARD_CONSTANTS}.cf_enhmetafile */
EIF_TYPED_VALUE F1021_9393 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

void EIF_Minit1021 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
